import './styles/prisme.css'

import { componentRegistry } from './components/registry'

export const {
  PrAccordion,
  PrAlert,
  PrAlertDialog,
  PrAppShell,
  PrBadge,
  PrButton,
  PrCalendar,
  PrCard,
  PrCarousel,
  PrCheckbox,
  PrCollapsible,
  PrCombobox,
  PrCommand,
  PrDataTable,
  PrDatePicker,
  PrDialog,
  PrDivider,
  PrDropdownMenu,
  PrFileUpload,
  PrHoverCard,
  PrInput,
  PrLabel,
  PrListItem,
  PrNavbar,
  PrNavigationMenu,
  PrPagination,
  PrPopover,
  PrProgress,
  PrRadioGroup,
  PrScrollArea,
  PrSelect,
  PrSheet,
  PrSidebar,
  PrSidebarItem,
  PrSidebarSubItem,
  PrSkeleton,
  PrSlider,
  PrSpinner,
  PrStepper,
  PrSwitch,
  PrTable,
  PrTabs,
  PrTextarea,
  PrThemeToggle,
  PrToast,
  PrToastProvider,
  PrToggle,
  PrToggleGroup,
  PrTooltip,
  PrTypography,
} = componentRegistry

export type {
  PrAccordionItem,
  PrAccordionProps,
  PrAlertDialogProps,
  PrAlertProps,
  PrAppShellProps,
  PrBadgeProps,
  PrButtonProps,
  PrCalendarProps,
  PrCardProps,
  PrCarouselItem,
  PrCarouselProps,
  PrCheckboxProps,
  PrCollapsibleProps,
  PrComboboxOption,
  PrComboboxProps,
  PrCommandItem,
  PrCommandProps,
  PrDataTableColumn,
  PrDataTableProps,
  PrDatePickerProps,
  PrDialogProps,
  PrDividerProps,
  PrDropdownMenuProps,
  PrFileUploadProps,
  PrHoverCardProps,
  PrInputProps,
  PrLabelProps,
  PrListItemProps,
  PrNavbarProps,
  PrNavigationMenuItem,
  PrNavigationMenuProps,
  PrPaginationProps,
  PrPopoverProps,
  PrProgressProps,
  PrRadioGroupProps,
  PrRadioOption,
  PrRejectedFile,
  PrScrollAreaProps,
  PrSelectOption,
  PrSelectProps,
  PrSheetProps,
  PrSidebarItemProps,
  PrSidebarProps,
  PrSidebarSubItemProps,
  PrSkeletonProps,
  PrSliderProps,
  PrSpinnerProps,
  PrStep,
  PrStepperProps,
  PrSwitchProps,
  PrTab,
  PrTableProps,
  PrTabsProps,
  PrTextareaProps,
  PrThemeToggleProps,
  PrToastProps,
  PrToastProviderProps,
  PrToggleGroupItem,
  PrToggleGroupProps,
  PrToggleProps,
  PrTooltipProps,
  PrTypographyProps,
} from './components/registry'

export { default, Prisme } from './plugin'

export {
  applyPrThemePreference,
  getPrThemeInitScript,
  PR_THEME_STORAGE_KEY,
  setPrTheme,
  togglePrTheme,
  usePrTheme,
} from './composables/usePrTheme'
export type { PrResolvedTheme, PrTheme } from './composables/usePrTheme'

export {
  email,
  fromLaravelErrors,
  max,
  maxLength,
  min,
  minLength,
  pattern,
  required,
  usePrForm,
} from './composables/usePrForm'
export type {
  LaravelValidationErrors,
  PrFieldConfig,
  PrFormReturn,
  PrFormSchema,
  PrValidationRule,
} from './composables/usePrForm'
